Implemented new feature: display last error log in scenario description
reportportal/agent-java-karate pull request #24
Opened 2024-03-04 12:04 UTC by vrymar

- Implemented new feature: display last error log in scenario description
- Implemented unit tests for the new feature
- Improved dependencies references in build.gradle

2024-03-05 16:05 UTC, vrymar commented
@HardNorth could you please review this PR?

2024-03-05 18:12 UTC, HardNorth commented
@vrymar Sure, will do this tomorrow.

2024-03-06 11:21 UTC, vrymar commented on CHANGELOG.md
> +## [5.0.4]
Should I put it under [Unreleased] ?
E.g.:
## [Unreleased]
### Added
- Implemented new feature: display last error log in scenario description, by @vrymar
- Implemented unit tests for the new feature, by @vrymar
### Changed
- Improved dependencies references in build.gradle, by @vrymar

2024-03-06 11:28 UTC, vrymar commented on src/main/java/com/epam/reportportal/karate/ReportPortalUtils.java
> +		if (parameters != null && !parameters.isEmpty()) {
But this one may return null: https://github.com/reportportal/agent-java-karate/blob/7710c7fe5fbd37272ab7b1061543a27f9ce40581/src/main/java/com/epam/reportportal/karate/ReportPortalUtils.java#L279

2024-03-06 11:30 UTC, HardNorth commented on src/main/java/com/epam/reportportal/karate/ReportPortalUtils.java
> +		if (parameters != null && !parameters.isEmpty()) {
Ok, missed that.

2024-03-06 11:30 UTC, HardNorth commented on CHANGELOG.md
> +## [5.0.4]
@vrymar Yes, exactly.

2024-03-06 13:43 UTC, HardNorth requested changes

2024-03-06 13:43 UTC, HardNorth commented on CHANGELOG.md
> -- Shutdown hook register on supplied Launch, by @HardNorth
Please don't revert my changes.

2024-03-06 16:35 UTC, HardNorth approved these changes

2024-03-06 16:35 UTC, merged